A branch to support WindowsError in RPython: today, raising a WindowsError in RPython actually sets an OSError which errno attribute is set to the value of GetLastError().
This is a problem at least in os.path.abspath, which expects WindowsError,
and for py.path.local.check(), which relies on the exception errno.

For example, today we have:

>>>> os.path.abspath("x"*300)
# should not fail
OSError: [Errno 183] Unknown error

>>>> os.stat("aaaa/bbbb")
# expected: WindowsError(winerror=3, errno=2)
OSError: [Errno 3] No such process